image:
  file: gitpod/.gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      bundle install
    command: >
      rails server
vscode:
  extensions:
    - rebornix.ruby
