default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] || 'postgres' %>
  username: <%= ENV['DATABASE_USER'] || 'gitpod' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'gitpod' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default
  database: postgres_test

production:
  <<: *default